---
- hosts: all
  become: yes
  roles:
     - hostname          # Set hostname and change /etc/hosts file
     - ipa-pkgs          # Install Free IPA server Packages
     - ipaclient-install # Configure Free IPA server
