---
# tasks file for server
#
#

- name: include vars from file
  include_vars:
    file: "vars/default.yml"

- name: Configuring IPA server
  command: ipa-client-install --domain={{ ipaserver_domain }} --server={{ ipaserver }}  --hostname {{ hostname }} --mkhomedir -p {{ ipa_username }} -w {{ ipaadmin_password }} -U
  ignore_errors: yes
  become: yes
